name: CI

on: [push, pull_request]

jobs:

  test-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: cache coderrect
      id: cache-coderrect
      uses: actions/cache@v2
      with:
        path: coderrect-linux-0.6.0
        key: ${{ runner.os }}-coderrect

    - name: setup coderrect
      if: steps.cache-coderrect.outputs.cache-hit != 'true'
      run: |
        wget https://public-installer-pkg.s3.us-east-2.amazonaws.com/coderrect-linux-0.6.0.tar.gz
        tar xfz coderrect-linux-0.6.0.tar.gz

    - name: make
      run: |
        export PATH=$PWD/coderrect-linux-0.6.0/bin:$PATH
        coderrect -t -all make
    
    - name: test
      run: |
        sudo apt-get install tcl8.5
        ./runtest --verbose
    - name: module api test
      run: ./runtest-moduleapi --verbose
